<?php $priorities = $block->getPriorityData(); ?>

<script id="add_input_tmpl" type="text/x-magento-template">
	<div class="actions-toolbar">
		<div class="secondary t_remove">
			<button type="button" id="btn-remove<%- data._index_ %>" class="remove_attachment"
				title="<?php echo $block->escapeHtmlAttr(__('Remove Attachment')) ?>"></button>
		</div>
		<div class="field">
			<div class="control">
				<input id="attachment<%- data._index_ %>" name="attachment[]" type="file" class="attachment" multiple="multiple" accept="image" />
			</div>
		</div>
	</fieldset>
</script>

<div class="tracking_wrap">
	<div class="title">
		<h2><?php echo $block->getDepartmentNameById($this->getDepartmentId()); ?></h2>
	</div>
	<form action="<?php echo $block->getSubmitAction(); ?>" method="post" class="ticket_form" enctype="multipart/form-data"
		data-mage-init='{
				"rowBuilder":{
					"rowTemplate":"#add_input_tmpl",
					"rowContainer":"#upload_inputs",
					"rowParentElem":"<div></div>",
					"remEventSelector":"button",
					"btnRemoveSelector":".remove_attachment",
					"maxRows":"<?php echo (int)$block->getMaxAttachments() ?>",
					"maxRowsMsg":"#max_attachments_message",
					"addRowBtn":"#add_input",
					"additionalRowClass":"attachment_item"
				},
				"validation":{}
			}'>
		<fieldset class="fieldset">
			<input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
			<input type="hidden" name="department_id" value="<?php echo $this->getDepartmentId(); ?>">
			<p>
				<label for="ticket_priority"><?php echo __('Priority'); ?></label>
				<select id="ticket_priority" name="priority_id" data-validate="{required:true, 'validate-select':true}">
					<?php foreach ($priorities as $priority): ?>
						<option value="<?php echo $priority['value']; ?>"><?php echo $priority['label']; ?></option>
					<?php endforeach; ?>
				</select>
			</p>
			<p>
				<label for="user_email"><?php echo __('Email'); ?></label>
				<input type="email" id="user_email" name="email" data-validate="{required:true, 'validate-email':true}" placeholder="<?php echo __('Email Address'); ?>">
			</p>
			<p>
				<label for="user_message"><?php echo __('Message'); ?></label>
				<textarea id="user_message" name="message_text" data-validate="{required:true}" placeholder="<?php echo __('Message'); ?>"></textarea>
			</p>
			<p id="wrap_inputs">
				<label><?php echo __('Upload File'); ?></label>
				<div class="actions t_actions">
					<div class="secondary">
					<?php if ($block->getMaxAttachments() > 1): ?>
						<button type="button" id="add_input" class="action add">
							<span><?php echo $block->escapeHtml(__('Add Attachment')) ?></span></button>
					<?php endif; ?>
					</div>
				</div>
				<div class="upload_inputs" id="upload_inputs"></div>
				
				<?php if ($block->getMaxAttachments()): ?>
					<div id="max_attachments_message" style="display: none;" class="message notice limit" role="alert">
						<span><?php echo $block->escapeHtml(__('Maximum %1 attachments allowed.', $block->getMaxAttachments())) ?></span>
					</div>
				<?php endif; ?>
			</p>
			<div class="actions-toolbar">
				<div class="primary">
					<button type="submit" title="Submit" class="action submit primary">
						<span><?php echo __('Submit'); ?></span>
					</button>
				</div>
			</div>
		</fieldset>
	</form>
</div>