<?php $ticketData = $block->getTicketDataById($this->getTicketId()); ?>

<div class="ticket_view_wrap">
	<div class="ticket_head separated">
		<h2><?php echo __("Details"); ?></h2>
		<p>
			<span><?php echo __("Ticket ID:"); ?><span class="head_value"><?php echo $ticketData['ticket_id']; ?></span></span>
			<span><?php echo __("Status:"); ?><span class="head_value"><?php echo $ticketData['status_value']; ?></span></span>
		</p>
		<p>
			<span><?php echo __("Department:"); ?><span class="head_value"><?php echo $ticketData['department_name']; ?></span></span>
			<span><?php echo __("Priority:"); ?><span class="head_value"><?php echo $ticketData['priority_value']; ?></span></span>
		</p>
		<p>
			<span><?php echo __("Created:"); ?><span class="head_value convert_date"><?php echo $ticketData['created_at']; ?></span></span>
			<span><?php echo __("Updated:"); ?><span class="head_value convert_date"><?php echo $ticketData['updated_at']; ?></span></span>
		</p>
	</div>
	
	<?php echo $block->getChildHtml('user.message'); ?>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'Tech_TaskTracking/js/date-converter'
	], function($, dateConverter) {
		var dataArray = $(".convert_date");
		$.each(dataArray, function (key, value) {
			$(value).text(dateConverter($(value).text(), 'DD.MM.YYYY'));
			$(value).css('opacity', 1);
		});
	});
</script>